### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by scoob212** [superyu1337/radarflow2#10]
error[E0433]: failed to resolve: could not find `game_info` in `offsets`
  --> src\dma\context\mod.rs:21:55
   |
21 |         let offset_build_number = cs2dumper::offsets::game_info::buildNumber;
   |                                                       ^^^^^^^^^ could not find `game_info` in `offsets`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `radarflow` (bin "radarflow" test) due to previous error

**Comment by superyu1337** [comment]
Issue is in cs2dumper currently. In the meantime, you can either clone cs2dumper, fix it, and generate new offsets for radarflow2 to use, or wait. I'll take a deeper look later.

**Comment by superyu1337** [comment]
Should hopefully be fixed now. A2X just pushed new files.
