### ISSUE TITLE
for some queastions plz

### ISSUE THREAD

**Issue by IDhammaI** [superyu1337/radarflow2#11]
Is it necessary to install an Ubuntu system to use this program, virtualize a Windows 10 computer on the Ubuntu system, and have the Ubuntu system read the memory of the virtualized Windows 10 computer for gaming?

**Comment by good1uck** [comment]
same question here, should the game run on linux?

**Comment by superyu1337** [comment]
> same question here, should the game run on linux?  

The game runs inside the virtual machine. This cheat runs on the host (linux) instead.


> Is it necessary to install an Ubuntu system to use this program, virtualize a Windows 10 computer on the Ubuntu system, and have the Ubuntu system read the memory of the virtualized Windows 10 computer for gaming?  

Yes, but it doesn't need to be Ubuntu specifically, I personally run archlinux.
There is also the possibility of using actual DMA hardware to run this too.
