### ISSUE TITLE
radarflow2 broken

### ISSUE THREAD

**Issue by Coforgqwq** [superyu1337/radarflow2#13]
Perhaps you can create a tutorial video and post it on YouTube?"
I am a user from China, and I really don't know how to install the Memflow plugin. Even after compiling everything, I still can't figure it out. Please, help me solve this problem. I really want to use this program. Thank you very much for your help.
![Uploading 9117f47b-bf66-4e09-bc38-c532f8fe2f31.png…]()

**Comment by Coforgqwq** [comment]
![Uploading 9117f47b-bf66-4e09-bc38-c532f8fe2f31.png…]()

**Comment by Coforgqwq** [comment]
error: failed to run custom build command for `radarflow v0.2.2 (/home/coforg/Build/radarflow2-main)`

Caused by:
  process didn't exit successfully: `/home/coforg/Build/radarflow2-main/target/release/build/radarflow-19c5f3ba1d241999/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at build.rs:7:29:
  Downloading "./src/dma/cs2dumper/client.rs"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by Coforgqwq** [comment]
error: failed to run custom build command for `radarflow v0.2.2 (/home/coforg/radarflow2)`

Caused by:
  process didn't exit successfully: `/home/coforg/radarflow2/target/release/build/radarflow-19c5f3ba1d241999/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at build.rs:7:29:
  Downloading "./src/dma/cs2dumper/client.rs"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
root@coforg:/home/coforg/radarflow2#

**Comment by superyu1337** [comment]
It seems there is some issue when downloading the offsets, which are used at compile time.
I see you are running as root, try to run as a user instead.

**Comment by dreambeaitbos** [comment]
> It seems there is some issue when downloading the offsets, which are used at compile time. I see you are running as root, try to run as a user instead.

i meet this erro too，should i how to do？

**Comment by dreambeaitbos** [comment]
> 非常感谢您的帮助。我在 build.sh 中将下载转储程序从 URL 更改为手动更新偏移量以解决此问题。但是现在a2x的自卸车存在一些问题。看来你的雷达不能使用他的翻斗车，现在他的文件被改成了。 client.dll.rs、engine2.dll.rs。Offsets.rs 没有改变。但是，如果输入cargo run，则会出现以下错误： ![1](https://private-user-images.githubusercontent.com/163156194/319181827-812523fc-e39f-4867-9a8e-b4d6132f4925.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNDg0MTMsIm5iZiI6MTcxMjE0ODExMywicGF0aCI6Ii8xNjMxNTYxOTQvMzE5MTgxODI3LTgxMjUyM2ZjLWUzOWYtNDg2Ny05YThlLWI0ZDYxMzJmNDkyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QxMjQxNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGUxN2Q3ZTMwNDUyOTNjZDU4ZGIzNzYyMTM4NzFhMGM3OWI2Y2ZjNWUwN2VlYjE0MjFmMmRhMWJlNzcwZWFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NPCi00uhfFKb9KzunZ8P1zPkHKE9KeZUooEHx83A98Y) ![2](https://private-user-images.githubusercontent.com/163156194/319181845-46f01052-b238-4faf-afcd-7ab4e11b2809.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNDg0MTMsIm5iZiI6MTcxMjE0ODExMywicGF0aCI6Ii8xNjMxNTYxOTQvMzE5MTgxODQ1LTQ2ZjAxMDUyLWIyMzgtNGZhZi1hZmNkLTdhYjRlMTFiMjgwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QxMjQxNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MDZjNWM1OTJlMDViMDVlMmFjNzRmZWNjMTMyN2M2NWM1YTA0MGEyM2VjYTFhNzgyMWZlY2VkM2U5NTA5NDAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F6uAtXi7j5ACijWjHNBIXTWOJedJTJLKSK1OUv-PqjA) ![1](https://private-user-images.githubusercontent.com/163156194/319183661-a9f38701-de33-4877-817d-5eb9afeacbc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNDg0MTMsIm5iZiI6MTcxMjE0ODExMywicGF0aCI6Ii8xNjMxNTYxOTQvMzE5MTgzNjYxLWE5ZjM4NzAxLWRlMzMtNDg3Ny04MTdkLTVlYjlhZmVhY2JjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QxMjQxNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTYyMzFhYjY1M2Q1ZmQwNTU0MzU4Y2Y4MWE3NTkxM2E2NWFlZTY1NTVkZjE3ZWIxMDM1MjFlNDI3N2Q5Y2FhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bw8cpe3jofcM5LITvvYpclmbLV9z6xW6WPTzS1Q13tI)

me too

**Comment by Coforgpaper** [comment]
@dreambeaitbos QAQ

**Comment by superyu1337** [comment]
It seems there has been a major change in the way cs2dumper works. I'll fix it when I have time, but I can't say when that will be, as I'm not really motivated to work on this project.

**Comment by superyu1337** [comment]
I've just pushed an update that bumps all dependencies and fixes the cs2dumper issue. It now compiles on my end, however I haven't tested functionality yet.
Could you try to test it again?

**Comment by Coforgpaper** [comment]
> 我刚刚推送了一个更新，该更新会颠簸所有依赖项并修复 cs2dumper 问题。它现在在我这边编译，但我还没有测试功能。你能再试一次测试吗？

i can try

**Comment by Coforgpaper** [comment]
@superyu1337 Sorry, something went wrong with my virtual machine just now. I will try to use it in about 10 hours. Thank you for your update!

**Comment by lukrei** [comment]
It says that game build is not right even if i use your new version. game build is 32767, but offsets are for 14000 when try to start it. i also tried to compile cs2dumper inside my vm and tried to run the files but it seems that cs2dumper produces no offsets in 2 files:
This files are empty:
client_mod.rs, engine2_mod.rs
Only offsets_mod.rs contains offsets.

**Comment by Coforgpaper** [comment]
If I want to update the offset manually, should I put client.dll.rs, engine2.dll.rs, offsets.rs or put them in Radarflow2/src/dma/cs2dumper?

**Comment by lukrei** [comment]
radarflow2/src/dma/cs2dumper should be the correct location but the namings are different. rename it to client_mod.rs, engine2_mod.rs and offsets_mod.rs.
Unfortunately it wont help much since two of the files are empty so radarflow2 wont work until this has been fixxed.

**Comment by lukrei** [comment]
Also be aware that offset dumper also works from qemu with this command line parameter: sudo ./cs2-dumper -c qemu

**Comment by superyu1337** [comment]
It seems there is a more major upstream issue (a2x/cs2-dumper/issues/106)
We'll need to wait until a2x has fixed the dumper. For now, it  *may* work using the pre-generated offsets that radarflow2 pulls from cs2-dumper's git repository. Manually editing offsets and disabling the build.rs is not intended to be done nor supported.

**Comment by superyu1337** [comment]
> It does not work. I tried both the new Offsets pregenerated from your cs2-dumper and from a2x both does not work.

Well then there is nothing we can do atm other than wait, in the meantime I'll set up my VM again so I can actually test.

**Comment by Coforgpaper** [comment]
> > 这是行不通的。我尝试了从您的 cs2-dumper 和 a2x 预生成的新偏移量都不起作用。
> 
> 那么除了等待之外，我们无能为力，与此同时，我将再次设置我的虚拟机，以便我可以实际测试。

@superyu1337 I tested the new radar2 five hours ago, and I found that he prompted me that I couldn't find the game. Is this caused by the bug of a2x's dumper?
![Uploading 1.png…]()

**Comment by Coforgpaper** [comment]
![Uploading 1.png…]()

**Comment by Coforgpaper** [comment]
> > It does not work. I tried both the new Offsets pregenerated from your cs2-dumper and from a2x both does not work.
> 
> Well then there is nothing we can do atm other than wait, in the meantime I'll set up my VM again so I can actually test.

@superyu1337 I tested the new radar2 five hours ago, and I found that he prompted me that I couldn't find the game. Is this caused by the bug of a2x's dumper?
![1](https://github.com/superyu1337/radarflow2/assets/163156194/7f0eb19e-2738-4e02-b56c-332ec4ea2d49)

**Comment by Coforgpaper** [comment]
Ax2' s dumper tool has been fixed, but I will still prompt this if I replace it in the radar directory:[game build is 14001, but offsets are for 14000]

**Comment by lukrei** [comment]
for me it is working again.

**Comment by Coforgpaper** [comment]
> for me it is working again. Can you try if you can run my Repository https://github.com/lukrei/Triggerflow-Client

omg
I'll try it later, and it's exciting to add triggerbot.！

**Comment by superyu1337** [comment]
> @superyu1337  Ax2' s dumper tool has been fixed, but I will still prompt this if I replace it in the radar directory:[game build is 14001, but offsets are for 14000]

Use the new CLI flag that should skip the version check. I'll look into it soon.

**Comment by Coforgpaper** [comment]
> > Ax2 的 dumper 工具已修复，但如果我在雷达目录中替换它，我仍然会提示此：[游戏版本为 14001，但偏移量为 14000]
> 
> 使用应跳过版本检查的新 CLI 标志。我很快就会调查的。

I can already use it. I rebuilt radarflow2.
So it can be used.
I just don't know if I can extract the dumper of CS2 through the exe program provided by a2x.
Can you directly rename and replace _mod.rs in the radarflow2/src/dma/cs2dumper directory?

**Comment by dreambeaitbos** [comment]
> > > Ax2 的 dumper 工具已修复，但如果我在雷达目录中替换它，我仍然会提示此：[游戏版本为 14001，但偏移量为 14000]
> > 
> > 
> > 使用应跳过版本检查的新 CLI 标志。我很快就会调查的。
> 
> I can already use it. I rebuilt radarflow2. So it can be used. I just don't know if I can extract the dumper of CS2 through the exe program provided by a2x. Can you directly rename and replace _mod.rs in the radarflow2/src/dma/cs2dumper directory?

哥们有扳机吗

**Comment by lukrei** [comment]
> > > Ax2 的 dumper 工具已修复，但如果我在雷达目录中替换它，我仍然会提示此：[游戏版本为 14001，但偏移量为 14000]
> > 
> > 
> > 使用应跳过版本检查的新 CLI 标志。我很快就会调查的。
> 
> I can already use it. I rebuilt radarflow2. So it can be used. I just don't know if I can extract the dumper of CS2 through the exe program provided by a2x. Can you directly rename and replace _mod.rs in the radarflow2/src/dma/cs2dumper directory?

I would not start the cs2-dumper inside your VM because it has potential to vac ban your account eventually.
instead git clone cs2-dumper on your hypervisor and run it there with this command line while cs2 is running inside your vm:
sudo ./cs2-dumper -c qemu

**Comment by Coforgpaper** [comment]
> 拟机中运行时，Git 克隆虚拟机管理程序上的 cs2-dumper，并使用此命令行

Maybe I didn't describe it clearly. I understand that I run radar2 on ubuntu. Then I run the game in the Windows10 virtual machine.
I just don't know about file replacement. Thank you very much for telling me. Now I understand.

**Comment by 1157265799** [comment]
> 错误：无法运行自定义构建命令`radarflow v0.2.2 (/home/coforg/radarflow2)`
> 
> 原因： 进程未成功退出：（`/home/coforg/radarflow2/target/release/build/radarflow-19c5f3ba1d241999/build-script-build`退出状态：101） ---stderr 线程'main'在build.rs:7:29处惊慌： 正在下载“./src/dma/cs2dumper/client.rs” 注意：使用`RUST_BACKTRACE=1`环境变量运行以显示回溯 root@coforg:/home/coforg/radarflow2#

Hello, may I ask how you solve this error later, I have also encountered this error now
![image](https://github.com/superyu1337/radarflow2/assets/119467320/bbae9fc5-2246-4e20-bcdb-d932a2d103fb)

**Comment by dreambeaitbos** [comment]
> > 错误：无法运行自定义构建命令`radarflow v0.2.2 (/home/coforg/radarflow2)`
> > 原因： 进程未成功退出：（退出状态：101） ---stderr 线程'main'在build.rs：7：29处惊慌： 正在下载“./src/dma/cs2dumper/client.rs” 注意：使用环境变量运行以显示回溯 root@coforg：/home/coforg/radarflow2#`/home/coforg/radarflow2/target/release/build/radarflow-19c5f3ba1d241999/build-script-build``RUST_BACKTRACE=1`
> 
> 您好，请问您稍后如何解决此错误，我现在也遇到了此错误 ![image](https://private-user-images.githubusercontent.com/119467320/320260452-bbae9fc5-2246-4e20-bcdb-d932a2d103fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0Nzc0MjAsIm5iZiI6MTcxMjQ3NzEyMCwicGF0aCI6Ii8xMTk0NjczMjAvMzIwMjYwNDUyLWJiYWU5ZmM1LTIyNDYtNGUyMC1iY2RiLWQ5MzJhMmQxMDNmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwODA1MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmY2ZDJmZmFjY2QyNTM5YjFhNTk2MDNmMmU1ZmVhNDQ4ZWQzNzQxZDk0YTQ3OTY3ZjM2NGY5NjhjNjBhMjYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lrKTqGAxU0DOCgY9GKnCg6Sje1per4qxKMGy-6AfCo0)

easy

**Comment by 1157265799** [comment]
> > > 错误：无法运行自定义构建命令`radarflow v0.2.2 (/home/coforg/radarflow2)`
> > > 原因： 进程未成功退出：（退出状态：101） ---stderr 线程'main'在build.rs：7：29处惊慌： 正在下载“./src/dma/cs2dumper/client.rs” 注意：使用环境变量运行以显示回溯 root@coforg：/home/coforg/radarflow2#`` /home/coforg/radarflow2/target/release/build/radarflow-19c5f3ba1d241999/build-script-build``RUST_BACKTRACE=1 ``
> > 
> > 
> > 您好，请问您稍后如何解决此错误，我现在也遇到了此错误 ![image](https://private-user-images.githubusercontent.com/119467320/320260452-bbae9fc5-2246-4e20-bcdb-d932a2d103fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0Nzc0MjAsIm5iZiI6MTcxMjQ3NzEyMCwicGF0aCI6Ii8xMTk0NjczMjAvMzIwMjYwNDUyLWJiYWU5ZmM1LTIyNDYtNGUyMC1iY2RiLWQ5MzJhMmQxMDNmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwODA1MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmY2ZDJmZmFjY2QyNTM5YjFhNTk2MDNmMmU1ZmVhNDQ4ZWQzNzQxZDk0YTQ3OTY3ZjM2NGY5NjhjNjBhMjYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lrKTqGAxU0DOCgY9GKnCg6Sje1per4qxKMGy-6AfCo0)
> 
> easy

Is the automatic download offset changed to manual update offset? If so, how to modify it

**Comment by superyu1337** [comment]
I've set up my VM again, and tested.
Everything works how it's supposed to work.

Make sure that the cs2dumper repository is reachable, otherwise the build.rs can't download the offsets.  
As for memflow modules, install memflowup and with it, install the `memflow-win32` and `memflow-qemu` modules from the stable channel.
