### ISSUE TITLE
Now there are some problems with a2x's dumper. It seems that your Radar can't use his dumper, and now his file is changed to. client.dll.rs、engine2.dll.rs。 Offsets.rs has not changed. However, if you enter cargo run, this error will appear:

### ISSUE THREAD

**Issue by Coforgpaper** [superyu1337/radarflow2#15]
Thank you very much for your help. I changed the download dumper from URL in build.sh to manually update the offset to solve this problem. But now there are some problems with a2x's dumper. It seems that your Radar can't use his dumper, and now his file is changed to.
client.dll.rs、engine2.dll.rs。 Offsets.rs has not changed. However, if you enter cargo run, this error will appear:
![1](https://github.com/superyu1337/radarflow2/assets/163156194/0619c279-23e9-46bb-a4d1-96573275df55)
![2](https://github.com/superyu1337/radarflow2/assets/163156194/60fb75ae-dae8-4f89-862b-451f9bc48b72)

**Comment by Coforgpaper** [comment]
![1](https://github.com/superyu1337/radarflow2/assets/163156194/6a157e96-c8e0-4f84-910d-5a1d30330e0b)

**Comment by superyu1337** [comment]
moved to #16
