### ISSUE TITLE
failed to run custom build command for `radarflow v0.2.3

### ISSUE THREAD

**Issue by 1157265799** [superyu1337/radarflow2#17]
Hello, I am stuck in this step now, how to solve it
![image](https://github.com/superyu1337/radarflow2/assets/119467320/5c741ffc-56cc-4882-8be1-483ae47d748d)

**Comment by superyu1337** [comment]
I'll look into it soon.

**Comment by 1157265799** [comment]
> 我很快就会调查一下。

Have you found a solution? I heard people in the QQ group say that you can change some files to package。
I have thought about this matter for a long time and still have no solution

**Comment by 1157265799** [comment]
Is the automatic download offset changed to manual update offset? If so, how to modify it

**Comment by 1157265799** [comment]
> > 我很快就会调查一下。
> 
> Have you found a solution? I heard people in the QQ group say that you can change some files to package。 I have thought about this matter for a long time and still have no solution

Is the automatic download offset changed to manual update offset? If so, how to modify it

**Comment by superyu1337** [comment]
Can't replicate, make sure you pulled the latest commits, and that the cs2dumper repository is reachable.
