### ISSUE TITLE
run pcileech ...

### ISSUE THREAD

**Issue by Suspectxyzz** [superyu1337/radarflow2#18]
hi, how am I running in the windows version, I can't figure out how to add the content

![image](https://github.com/superyu1337/radarflow2/assets/45514952/74899a96-98fa-4b40-acae-e38a0bdc6ba3)

**Comment by superyu1337** [comment]
Refer to the memflow documentations or ask ko1n. I'd assume the memflow plugins need to be either next to the binary or in your global PATH variable.

**Comment by Suspectxyzz** [comment]
> Refer to the memflow documentations or ask ko1n. I'd assume the memflow plugins need to be either next to the binary or in your global PATH variable.

can you show me how you have the main folder with the radar?

![image](https://github.com/superyu1337/radarflow2/assets/45514952/a2e78fc7-5e6c-4c20-bb57-19a99153cc39)

**Comment by superyu1337** [comment]
You probably need to throw the DLL files into `target/release/` next to where `radarflow2.exe` should be.
