### ISSUE TITLE
After the cs2 update, the radar failed

### ISSUE THREAD

**Issue by 1157265799** [superyu1337/radarflow2#23]
Hello author, today cs2 has a small update, when the radar is turned on, it will only show my own dot, I tried to update the offset to fix it, but it doesn't seem to work

**Comment by Coforgpaper** [comment]
Yes, I have the same problem. radar only shows my own position, but neither the enemy nor my teammates can.

**Comment by superyu1337** [comment]
Please don't create issues about disfunctions after a game update. Those issues are upstream issues at [a2x/cs2-dumper](https://github.com/a2x/cs2-dumper). With that being said, don't create issues there either. a2x will update the pre-generated offsets once they have time.

**Comment by Coforgpaper** [comment]
> 请不要在游戏更新后制造有关功能失调的问题。这些问题是 [a2x/cs2-dumper](https://github.com/a2x/cs2-dumper) 的上游问题。话虽如此，也不要在那里制造问题。A2X 将在有时间后更新预先生成的偏移量。

okay thanks
