### ISSUE TITLE
cs2 pawn schema changed

### ISSUE THREAD

**Issue by dreambeaitbos** [superyu1337/radarflow2#26]
Hello, after the game is updated, I updated the offset in your project, but I reported an error during the compilation, I hope you can fix it, thank you very much!
Here are the error codes：
error[E0425]: cannot find value `dwBuildNumber` in module `cs2dumper::offsets::engine2_dll`
  --> src/dma/context/mod.rs:21:115
   |
21 | ...fsets::engine2_dll::dwBuildNumber)?;
   |                        ^^^^^^^^^^^^^ not found in `cs2dumper::offsets::engine2_dll`

error[E0425]: cannot find value `m_bIsScoped` in module `cs2dumper::client::C_CSPlayerPawnBase`
   --> src/dma/context/mod.rs:107:77
    |
107 |             batcher.read_into(pawn + cs2dumper::client::C_CSPlayerPawnBase::m_bIsScoped, &mut is_scoped);
    |                                                                             ^^^^^^^^^^^ not found in `cs2dumper::client::C_CSPlayerPawnBase`
    |
help: consider importing this constant
    |
1   + use crate::dma::cs2dumper::client::C_CSPlayerPawn::m_bIsScoped;
    |
help: if you import `m_bIsScoped`, refer to it directly
    |
107 -             batcher.read_into(pawn + cs2dumper::client::C_CSPlayerPawnBase::m_bIsScoped, &mut is_scoped);
107 +             batcher.read_into(pawn + m_bIsScoped, &mut is_scoped);
    |

warning: unused import: `crate::dma::cs2dumper::client::C_CSPlayerPawn::m_bIsScoped`
 --> src/dma/context/mod.rs:2:5
  |
2 | use crate::dma::cs2dumper::client::C_CSPlayerPawn::m_bIsScoped;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

For more information about this error, try `rustc --explain E0425`.
warning: `radarflow` (bin "radarflow") generated 1 warning
error: could not compile `radarflow` (bin "radarflow") due to 2 previous errors; 1 warning emitted

**Comment by superyu1337** [comment]
It compiles on my machine, unless cs2-dumper hat major changes since yesterday. Run `git pull` or clone the repo again. And don't manually update offsets, unless build.rs can't download them due to china firewall.

**Comment by dreambeaitbos** [comment]
> It compiles on my machine, unless cs2-dumper hat major changes since yesterday. Run `git pull` or clone the repo again. And don't manually update offsets, unless build.rs can't download them due to china firewall.
error: failed to run custom build command for `radarflow v0.2.4 (/home/pdx/radarflow2-development)`

Caused by:
  process didn't exit successfully: `/home/pdx/radarflow2-development/target/release/build/radarflow-0c790d396dea9698/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at build.rs:14:29:
  Downloading "./src/dma/cs2dumper/client_mod.rs"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by superyu1337** [comment]
Not really, only game updates. I already fixed radarflow2 for the recent restructure in cs2-dumper.

**Comment by dreambeaitbos** [comment]
> Not really, only game updates. I already fixed radarflow2 for the recent restructure in cs2-dumper.

I just used your branch and received this error message:

error[E0425]: cannot find value `m_bIsScoped` in module `cs2dumper::client::C_CSPlayerPawnBase`
   --> src/dma/context/mod.rs:108:77
    |
108 | ...t::C_CSPlayerPawnBase::m_bIsScoped, &mut is_scoped);
    |                           ^^^^^^^^^^^ not found in `cs2dumper::client::C_CSPlayerPawnBase`
    |
help: consider importing this constant
    |
1   + use crate::dma::cs2dumper::client::C_CSPlayerPawn::m_bIsScoped;
    |
help: if you import `m_bIsScoped`, refer to it directly
    |
108 -             batcher.read_into(pawn + cs2dumper::client::C_CSPlayerPawnBase::m_bIsScoped, &mut is_scoped);
108 +             batcher.read_into(pawn + m_bIsScoped, &mut is_scoped);
    |

For more information about this error, try `rustc --explain E0425`.
The following warnings were emitted during compilation:

warning: radarflow@0.2.4: not within a suitable 'git' worktree!
warning: radarflow@0.2.4: VERGEN_GIT_COMMIT_DATE set to default
warning: radarflow@0.2.4: VERGEN_GIT_SHA set to default

error: could not compile `radarflow` (bin "radarflow") due to 1 previous error

**Comment by superyu1337** [comment]
Try the development branch now.

**Comment by Coforgpaper** [comment]
> 立即试用开发分支。

Thank you for actively maintaining radar, one of the most perfect developers.
