### ISSUE TITLE
Understanding issue: Do you have to play CS2 from Linux for this to work?

### ISSUE THREAD

**Issue by FabianKielmann** [superyu1337/radarflow2#3]
The Readme says, "you need to set up a virtual machine on Linux." Or can I also create a Linux VM on a Windows system, run memflow with radarflow2 on the VM, and play CS2 on the host system? Would that work?

**Comment by lukrei** [comment]
You need a KVM Hypervisor which is Linux only. Setup a Linux Distro like Debian Trixie and get a 2nd GPU and create a windows vm inside your KVM Hypervisor. Then pass through your mouse, keyboard, headset (or pulseaudio) and your 2nd GPU.
Then you would have to setup memflow first before you can use radarflow2. And yes you have to start radarflow2 on linux.

In Windows you can open a Webgui then after you have started radarflow2 which is something like http://ipofyourkvmhypervisor:8000

**Comment by FabianKielmann** [comment]
Thanks for the clarification!

**Comment by superyu1337** [comment]
As lukrei said, radarflow2 is intended to run on a kvm hypervisor on Linux, to read memory from the vom, where the game runs on.

You can either do it like lukrei said, though you don't actually need two GPUs. Or you can use something like an M2 Screamer, which basically throws away the need for Linux and and a vm, but that method is costly and untested.
