### ISSUE TITLE
oslayer: module not found

### ISSUE THREAD

**Issue by colo808** [superyu1337/radarflow2#31]
![image](https://github.com/superyu1337/radarflow2/assets/149461288/d3bf5a6e-0544-46ec-83e9-a6369e0a7698)
![image](https://github.com/superyu1337/radarflow2/assets/149461288/e530194f-ab73-4e20-a005-50dd75962e68)

I'm trying to run it on windows 11, both connectors added to system environment path but meet with this error, can't find any information about oslayers

##EDIT

I have reinstalled memflow plugins, now it prints the configspace of FPGA however same error still occur
![image](https://github.com/superyu1337/radarflow2/assets/149461288/92ca8fcf-04b1-4e61-b324-0aa63fec5314)

**Comment by superyu1337** [comment]
Those modules need to be either in PATH or next to the radarflow binary.
