### ISSUE TITLE
I turned on the radar, but it showed not on a server, and I entered the game.

### ISSUE THREAD

**Issue by Coforgpaper** [superyu1337/radarflow2#35]
![a9b56207ecbfda6275b086e736edd062](https://github.com/superyu1337/radarflow2/assets/163156194/5f55d2bb-9751-4fd1-bd88-4e6adf4d7edd)
![ea81a3bb21077160637dc09baabf8f7a_720](https://github.com/superyu1337/radarflow2/assets/163156194/c5ea6faf-5e66-4bb2-ba7e-dadf520f87e0)
![559feacb0908167d819073d1923d3fbd_720](https://github.com/superyu1337/radarflow2/assets/163156194/f3330ede-2c0e-4b08-afc8-4af7b8f50429)

**Comment by dreadjedreck** [comment]
me  too

**Comment by dgw2486** [comment]
me too

**Comment by Polarisjl** [comment]
Hi guys I figured it out.
After game updated recently, the map name string offset changed.
To solve this, just look for `src/dma/threaddata/mod.rs`, line 168 should be :
`let map_addr = (self.globals + 0x188).into();`
change the `0x188` in code to `0x1B8` should work.

**Comment by Coforgpaper** [comment]
> 嗨，大家好，我想通了。最近游戏更新后，地图名称字符串偏移量发生了变化。要解决这个问题，只需查找 ，第 168 行应该是：将 in 代码更改为 should work。`src/dma/threaddata/mod.rs``let map_addr = (self.globals + 0x188).into();``0x188``0x1B8`

thanks you！！！！

**Comment by Coforgpaper** [comment]
> 嗨，大家好，我想通了。最近游戏更新后，地图名称字符串偏移量发生了变化。要解决这个问题，只需查找 ，第 168 行应该是：将 in 代码更改为 should work。`src/dma/threaddata/mod.rs``let map_addr = (self.globals + 0x188).into();``0x188``0x1B8`

i try

**Comment by dgw2486** [comment]
i cant

**Comment by dgw2486** [comment]
i cant
