### ISSUE TITLE
c9a253) error[E0425]: cannot find value dwGameEntitySystem_getHighestEntityIndex in module cs2dumper::offsets::client_dll --> src/dma/threaddata/mod.rs:181:91 | 181 | ...lient_dll::dwGameEntitySystem_getHighestEntityIndex as u64).into(); | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: dwGameEntitySystem_highestEntityIndex | ::: src/dma[表情]2dumper/offsets_mod.rs:13:13 | 13 | ... pub const dwGameEntitySystem_highestEntityIndex: usize = 0x1510; | ---------------------------------------------------------------- similarly named constant dwGameEntitySystem_highestEntityIndex defined here  For more information about this error, try rustc --explain E0425. The following warnings were emitted during compilation:

### ISSUE THREAD

**Issue by Coforgpaper** [superyu1337/radarflow2#42]
c9a253)
error[E0425]: cannot find value dwGameEntitySystem_getHighestEntityIndex in module cs2dumper::offsets::client_dll
--> src/dma/threaddata/mod.rs:181:91
|
181 | ...lient_dll::dwGameEntitySystem_getHighestEntityIndex as u64).into();
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: dwGameEntitySystem_highestEntityIndex
|
::: src/dma[表情]2dumper/offsets_mod.rs:13:13
|
13 | ... pub const dwGameEntitySystem_highestEntityIndex: usize = 0x1510;
| ---------------------------------------------------------------- similarly named constant dwGameEntitySystem_highestEntityIndex defined here

For more information about this error, try rustc --explain E0425.
The following warnings were emitted during compilation:
![e92e7ee195e7fb94956dcf6149961bc2](https://github.com/a2x/cs2-dumper/assets/163156194/ebb3b611-1ae6-4907-9321-5e754a97a888)

**Comment by dreadjedreck** [comment]
Rename dwGameEntitySystem_getHighestEntityIndex to dwGameEntitySystem_highestEntityIndex

**Comment by Coforgpaper** [comment]
> 将 dwGameEntitySystem_getHighestEntityIndex 重命名为 dwGameEntitySystem_highestEntityIndex

thanks
